### ISSUE TITLE
docs link is 404'd

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_BusDevice#39]
The link from README.rst, https://circuitpython.readthedocs.io/projects/bus_device/en/latest/ , does not work.  This is also causing doc build failures in repositories that refer to this one via intersphinx, such as at https://github.com/adafruit/Adafruit_CircuitPython_VL53L0X/runs/419328376 .

The docs appear to exist at https://circuitpython.readthedocs.io/projects/busdevice/en/latest/ instead (note the missing underscore).

If the link is wrong and needs to be updated, it looks like the following projects in Adafruit_Circuitpython_Bundle will need to have their intersphinx links updated:

- [x] https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing
- [x] https://github.com/adafruit/Adafruit_CircuitPython_BusDevice
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VL6180X
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx
- [x] https://github.com/adafruit/Adafruit_CircuitPython_TCS34725
- [x] https://github.com/adafruit/Adafruit_CircuitPython_AS726x
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VCNL4010
- [x] https://github.com/adafruit/Adafruit_CircuitPython_TSL2561
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SI4713
- [x] https://github.com/adafruit/Adafruit_CircuitPython_RFM9x
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VL53L0X
- [x] https://github.com/adafruit/Adafruit_CircuitPython_TSL2591
- [x] https://github.com/adafruit/Adafruit_CircuitPython_WS2801
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MPL3115A2
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VEML6070
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MMA8451
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SI5351

**Comment by ladyada** [comment]
@dherrada hi dylan, would you be up to fixing the URLs in these repos? wouldn't be automated, each one needs a _ removed

**Comment by evaherrada** [comment]
@ladyada sure

**Comment by evaherrada** [comment]
All PRs have been made. I accidentally pressed the wrong button and commited to master on VL6180X and MCP230xx.

**Comment by ladyada** [comment]
thats ok :)

**Comment by evaherrada** [comment]
@kattni (almost) all releases are in. I forgot to tag circuitpython librarians in a few of the PRs. Here are their links:

* https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/pull/53
* https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/pull/40

**Comment by kattni** [comment]
@dherrada Merged. Please release those two and then we can close this issue. Thanks!

**Comment by evaherrada** [comment]
I've done the last 2 releases. Closing
