### ISSUE TITLE
Should SPIDevice create a DigitalInputOutput object for the CS pin?

### ISSUE THREAD

**Issue by deshipu** [adafruit/Adafruit_CircuitPython_BusDevice#6]
Right now it doesn't, and that leads to some boilerplate code. On the other hand, that allows for some dependency injection, for instance using a dummy object for when we don't need CS, a mocked object for tests, etc. On the other hand (how many hands are there), the injection is not that useful, as there isn't any state or initialization possible on that object normally, and no CS could be communicated by passing None (or not passing a cs argument at all, letting it default to None).

**Comment by tannewt** [comment]
I prefer the dependency injection model. That way if someone is using an IO expander its easy to use an output line from it instead. When that isn't possible (like neopixel), the method should take a pin.
