### ISSUE TITLE
Error message gives a hex address without the 0x prefix

### ISSUE THREAD

**Issue by BiffoBear** [adafruit/Adafruit_CircuitPython_BusDevice#62]
adafruit_bus_device/i2c_device.py line 180
`                raise ValueError("No I2C device at address: %x" % self.device_address)`

would be better as;
`                raise ValueError("No I2C device at address: 0x%x" % self.device_address)`

as the hex address without a prefix is ambiguous.

**Comment by ladyada** [comment]
solved :)
