### ISSUE TITLE
Bus Device version '0.0.0-auto.0'

### ISSUE THREAD

**Issue by TinManAkshay** [adafruit/Adafruit_CircuitPython_BusDevice#66]
Hi,

When I run 'adafruit_bus_device.i2c_device.__version__' , it returns '0.0.0-auto.0'. I've python3.7 on Pi 3B+. I was wondering if there is any problem with the auto version or I have install some other version?

Thanks,
Akshay

**Comment by tannewt** [comment]
I don't think we replace it for the pypi package. You can use pip to see what version you have instead.

**Comment by tekktrik** [comment]
This is now fixed!  PyPI now has the correct `__version__` string.
