### ISSUE TITLE
add a note about CirPy v6.3.0+ having this lib baked in

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/Adafruit_CircuitPython_BusDevice#67]
I was wondering if it would be prudent to add a note (probably in the README) about how v6.3.0+ of Circuitpython firmware already has this lib included. I haven't checked thoroughly if this is true for all boards running CirPy (ie ATSAMD21)

After some testing, I found the `SPIDevice` class (from firmware) executes slightly faster than this pure python implementation. 💯

**Comment by tannewt** [comment]
Would you mind making a pull request? I like your idea.

**Comment by 2bndy5** [comment]
sure (I don't mind).
