### ISSUE TITLE
Need a way to create an SPI device without a chip select pin

### ISSUE THREAD

**Issue by deanm1278** [adafruit/Adafruit_CircuitPython_BusDevice#8]
e.g. `spi_device = SPIDevice(busio.SPI(board.SCK, board.MOSI, board.MISO), None, baudrate=4000000)`

This is for things like displays that have other signals to be managed during a transaction. We want to tell the busDevice to not worry about chip select, we will manage it ourselves manually.

**Comment by cerickson** [comment]
I'll work on this one.
