### ISSUE TITLE
I2C write error I2CDevice

### ISSUE THREAD

**Issue by Jerzeek** [adafruit/Adafruit_CircuitPython_BusDevice#98]
Hi folks! 
I have a strange problem with one of my I2C devices.
If I use the traditional try_lock() function, I get correct communication with my I2C device, If I use the improved I2CDevice, the communication stops.
This is the sample code I wrote to check my sanity:
```
import busio
import board
import time

#this works
i2c = busio.I2C(board.SCL, board.SDA)
while not i2c.try_lock():
    pass
try:
    i2c.writeto(0x0f, bytearray([0x84,0x02,0x01]))
    print("done one")

finally:
    i2c.unlock()

#this does not work....
from adafruit_bus_device.i2c_device import I2CDevice
device = I2CDevice(i2c, 0x0f)
with device:
    device.write(bytearray([0x84,0x02,0x01]))
    print("done two")
```

This is what I see on the logic analyser:
![image](https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/assets/22919620/e8cbdc92-0d08-48f9-9fad-e26f1ac7cc74)

It seems to be specific to the I2C device, it is a [grove i2c motor driver](https://wiki.seeedstudio.com/Grove-I2C_Motor_Driver_V1.3/)
I tried the same with a temperature sensor but that worked fine..

**Comment by caternuson** [comment]
The last write shown is actually coming from this line:
```python
device = I2CDevice(i2c, 0x0f)
```
since the I2CDevice does a device discovery check (probe) when created.

That is followed by a start that does nothing. That should be the start of the context manager.

Try suppressing the probe check and see if that changes the behavior.
```python
device = I2CDevice(i2c, 0x0f, probe=False)
```

**Comment by FoamyGuy** [comment]
Closing this for now. Please feel free to re-open if you get back to this and are still facing the same issue after trying the suggestion above.
